In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\train.csv")
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [ ]:
#The data is too big and we only need to consider the important columns,

In [15]:
df=df[["LotFrontage","LotArea","Street","RoofStyle","HouseStyle","BedroomAbvGr","KitchenAbvGr","GarageArea","SalePrice"]]
df

,LotFrontage,LotArea,Street,RoofStyle,HouseStyle,BedroomAbvGr,KitchenAbvGr,GarageArea,SalePrice
0,65.0,8450,Pave,Gable,2Story,3,1,548,208500
1,80.0,9600,Pave,Gable,1Story,3,1,460,181500
2,68.0,11250,Pave,Gable,2Story,3,1,608,223500
3,60.0,9550,Pave,Gable,2Story,3,1,642,140000
4,84.0,14260,Pave,Gable,2Story,4,1,836,250000
...,...,...,...,...,...,...,...,...,...
1455,62.0,7917,Pave,Gable,2Story,3,1,460,175000
1456,85.0,13175,Pave,Gable,1Story,3,1,500,210000
1457,66.0,9042,Pave,Gable,2Story,4,1,252,266500
1458,68.0,9717,Pave,Hip,1Story,2,1,240,142125
1459,75.0,9937,Pave,Gable,1Story,3,1,276,147500

# data preprocessing

In [17]:
df.isnull().sum()/len(df)*100

LotFrontage     17.739726
LotArea          0.000000
Street           0.000000
RoofStyle        0.000000
HouseStyle       0.000000
BedroomAbvGr     0.000000
KitchenAbvGr     0.000000
GarageArea       0.000000
SalePrice        0.000000
dtype: float64

In [ ]:
#fixing missing vals

In [19]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='mean')
si

SimpleImputer()

In [23]:
df["LotFrontage"]=si.fit_transform(df[["LotFrontage"]])
df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2224\603761758.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["LotFrontage"]=si.fit_transform(df[["LotFrontage"]])

,LotFrontage,LotArea,Street,RoofStyle,HouseStyle,BedroomAbvGr,KitchenAbvGr,GarageArea,SalePrice
0,65.0,8450,Pave,Gable,2Story,3,1,548,208500
1,80.0,9600,Pave,Gable,1Story,3,1,460,181500
2,68.0,11250,Pave,Gable,2Story,3,1,608,223500
3,60.0,9550,Pave,Gable,2Story,3,1,642,140000
4,84.0,14260,Pave,Gable,2Story,4,1,836,250000
...,...,...,...,...,...,...,...,...,...
1455,62.0,7917,Pave,Gable,2Story,3,1,460,175000
1456,85.0,13175,Pave,Gable,1Story,3,1,500,210000
1457,66.0,9042,Pave,Gable,2Story,4,1,252,266500
1458,68.0,9717,Pave,Hip,1Story,2,1,240,142125
1459,75.0,9937,Pave,Gable,1Story,3,1,276,147500

In [24]:
df.isnull().sum()   # all missing values are fixed

LotFrontage     0
LotArea         0
Street          0
RoofStyle       0
HouseStyle      0
BedroomAbvGr    0
KitchenAbvGr    0
GarageArea      0
SalePrice       0
dtype: int64

# feature encoding

In [28]:
df_ohe=pd.get_dummies(df[["Street","RoofStyle","HouseStyle"]])
df_ohe

,Street_Grvl,Street_Pave,RoofStyle_Flat,RoofStyle_Gable,RoofStyle_Gambrel,RoofStyle_Hip,RoofStyle_Mansard,RoofStyle_Shed,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl
0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0
1,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0
2,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0
3,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0
4,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0
1456,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0
1457,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0
1458,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0
1459,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0

In [29]:
df=pd.concat([df,df_ohe],axis=1)
df

,LotFrontage,LotArea,Street,RoofStyle,HouseStyle,BedroomAbvGr,KitchenAbvGr,GarageArea,SalePrice,Street_Grvl,...,RoofStyle_Mansard,RoofStyle_Shed,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl
0,65.0,8450,Pave,Gable,2Story,3,1,548,208500,0,...,0,0,0,0,0,0,0,1,0,0
1,80.0,9600,Pave,Gable,1Story,3,1,460,181500,0,...,0,0,0,0,1,0,0,0,0,0
2,68.0,11250,Pave,Gable,2Story,3,1,608,223500,0,...,0,0,0,0,0,0,0,1,0,0
3,60.0,9550,Pave,Gable,2Story,3,1,642,140000,0,...,0,0,0,0,0,0,0,1,0,0
4,84.0,14260,Pave,Gable,2Story,4,1,836,250000,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,62.0,7917,Pave,Gable,2Story,3,1,460,175000,0,...,0,0,0,0,0,0,0,1,0,0
1456,85.0,13175,Pave,Gable,1Story,3,1,500,210000,0,...,0,0,0,0,1,0,0,0,0,0
1457,66.0,9042,Pave,Gable,2Story,4,1,252,266500,0,...,0,0,0,0,0,0,0,1,0,0
1458,68.0,9717,Pave,Hip,1Story,2,1,240,142125,0,...,0,0,0,0,1,0,0,0,0,0
1459,75.0,9937,Pave,Gable,1Story,3,1,276,147500,0,...,0,0,0,0,1,0,0,0,0,0

In [33]:
df=df.drop(["Street","RoofStyle","HouseStyle"],axis=1)
df

,LotFrontage,LotArea,BedroomAbvGr,KitchenAbvGr,GarageArea,SalePrice,Street_Grvl,Street_Pave,RoofStyle_Flat,RoofStyle_Gable,...,RoofStyle_Mansard,RoofStyle_Shed,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl
0,65.0,8450,3,1,548,208500,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
1,80.0,9600,3,1,460,181500,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
2,68.0,11250,3,1,608,223500,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
3,60.0,9550,3,1,642,140000,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
4,84.0,14260,4,1,836,250000,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,62.0,7917,3,1,460,175000,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
1456,85.0,13175,3,1,500,210000,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
1457,66.0,9042,4,1,252,266500,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
1458,68.0,9717,2,1,240,142125,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
1459,75.0,9937,3,1,276,147500,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0

# feature scaling

In [34]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss

StandardScaler()

In [35]:
df[["LotFrontage","LotArea","GarageArea"]]=ss.fit_transform(df[["LotFrontage","LotArea","GarageArea"]])
df

,LotFrontage,LotArea,BedroomAbvGr,KitchenAbvGr,GarageArea,SalePrice,Street_Grvl,Street_Pave,RoofStyle_Flat,RoofStyle_Gable,...,RoofStyle_Mansard,RoofStyle_Shed,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl
0,-0.229372,-0.207142,3,1,0.351000,208500,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
1,0.451936,-0.091886,3,1,-0.060731,181500,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
2,-0.093110,0.073480,3,1,0.631726,223500,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
3,-0.456474,-0.096897,3,1,0.790804,140000,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
4,0.633618,0.375148,4,1,1.698485,250000,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,-0.365633,-0.260560,3,1,-0.060731,175000,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
1456,0.679039,0.266407,3,1,0.126420,210000,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
1457,-0.183951,-0.147810,4,1,-1.033914,266500,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
1458,-0.093110,-0.080160,2,1,-1.090059,142125,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
1459,0.224833,-0.058112,3,1,-0.921624,147500,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0

# DIVIDE X AND Y

In [37]:
x=df.drop(["SalePrice"],axis=1)
y=df["SalePrice"]

# split train test

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

# fit and apply linear regression

In [39]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr

LinearRegression()

In [40]:
lr.fit(x_train,y_train)

LinearRegression()

In [41]:
y_pred=lr.predict(x_test)
y_pred

array([189080.81738881, 125430.5373205 , 142081.29577554, 246767.45516928,
       129311.10037232, 148653.58673819, 223066.8041804 , 175985.12291823,
       340914.27647361, 186615.40394745, 145871.00974423, 141914.86882353,
       201405.18762908, 120794.56965987, 113280.64089703, 130318.92577998,
       228134.06441568,  67619.73721417, 125885.98312863, 126486.43677774,
       224322.76682375, 138237.10942098,  57850.60406685, 167277.29055371,
       250420.01615924, 219646.12485934, 181724.90904026,  27587.4108427 ,
       268568.1885591 , 137420.54899003, 219127.97566867, 188440.29331971,
       151176.38334466, 285873.75806779, 278152.35586161, 192548.31953445,
       204108.809884  , 163015.04190203, 233059.83403926, 257061.69563256,
       202775.46154296, 166994.5331895 , 150281.84950127, 260047.76693409,
       312180.74948368, 118585.97305688, 201942.14526388, 137335.41103614,
       224177.03114231, 126282.40559087, 265539.63952925, 212126.93204099,
       195999.48163372,  63866.85129326, 169666.49868418, 167487.450639  ,
       164170.36071293, 263877.75528956, 171463.70394348, 105565.18287475,
       164430.69266773, 163691.65971012, 157002.68506287, 192899.06129563,
       184646.49363092, 192328.86606972, 153247.66638342, 240551.68696436,
       174542.9745443 , 191801.57503002, 186786.1516947 ,  43852.6135953 ,
       194229.72651823, 174840.01461573, 129720.64220455, 247290.25782864,
       126183.55419694, 120655.15025993, 256435.07131364, 157570.64823535,
       187880.89212595, 137191.63527845,  98956.87325137, 202628.40494737,
       106877.58535821, 176188.97071568, 259536.53008374, 147961.427837  ,
       170264.05262688, 164342.00881235, 205756.15197307, 225619.56782309,
       187701.91972404, 213274.6861502 , 184047.91217263, 170652.77339702,
       192864.74772189, 172486.86219654, 163885.13826234, 136694.69388253,
       210029.34001639, 202282.87512767, 151584.16574222, 222261.06301617,
       158682.67141026, 257803.96664774, 167813.06259627, 124089.81821031,
       179659.87209327,  95431.90872814, 120698.37450459, 120139.17258974,
       213387.47929562, 152871.76121741, 217210.92833729, 166312.81294322,
       314637.79490138, 133816.69900412, 224342.48456833, 308366.61482499,
        68000.96363013, 184734.45195067, 220132.42132093, 206106.36968932,
       170798.82491193, 157493.87472635, 237436.46263445, 174849.29277679,
       156030.56708682, 182049.23098734, 171025.3412575 , 232033.14197938,
       176926.52961533, 169648.02907817, 128916.24775418, 225252.95783656,
       119441.5387488 , 177792.70973983, 111779.67159333, 194457.41685593,
       141170.37055849, 138759.85444985, 208024.40485786, 165800.71097096,
        81529.8742592 , 183935.30389076, 195271.01497534, 136401.07073707,
       208842.85543608, 183147.23359645, 199012.95004547, 300397.68259041,
       227223.43107588,  33656.89146711, 174898.75768492, 239171.98927677,
       222419.40588376, 184114.89922565,  71383.75074529, 136544.55864998,
       182730.58449016, 214387.52775896, 221603.94999685, 185102.99069712,
       242236.56432434,  78248.37714369, 158369.96674083, 283809.71053379,
       157983.66560164, 192977.64658942, 263484.84945011, 195943.21720262,
       167953.5335752 , 175988.41342781, 226591.46571021, 113351.24689436,
       114270.40873249, 241545.56742182, 138016.83293749, 169626.16233121,
       190241.57705023, 174087.9395746 , 140138.9766201 , 239081.44367117,
       170921.90197701, 218552.58271332, 126263.75123004, 188464.70903569,
       184047.91217263, 127019.40353433, 163846.31276614, 135013.69189302,
       180008.45984649, 169456.74476825, 194906.48497208, 163294.75290014,
        84408.35434573, 143027.81354622, 206161.852976  , 159413.44707248,
       161721.37091437, 145191.22697941, 248811.16210665,  68021.87573211,
        66738.13850889, 279460.05047218, 199977.71928103, 283382.64177903,
       260816.74060999,  56262.89377756, 191408.25276805, 151679.29832939,
        96611.03646982,  46574.98916683, 277294.93315448, 251335.34947468,
       221775.94734342, 230096.71069126, 244729.55499974,  27536.02647652,
       181410.25142099, 235455.29250295, 142856.78650036, 179718.43179105,
       137942.14533341, 282702.99965148, 216892.69433945, 212559.01290532,
       125847.85391083, 173032.64604442, 100021.14055918, 211256.34082456,
        73727.32466376, 144899.29280039, 218238.47440408, 126176.53071753,
        59004.58916651, 133703.0825548 ,  15323.56468637, 181508.09576813,
       102433.30717492, 219360.15219253, 200107.89658541, 224909.87721083,
       168330.12471107, 152093.36966472, 168841.94201343, 202638.52624827,
       139600.01862722, 204903.38065004, 192974.77165374, 318963.80350377,
        55317.15005094, 265904.10763669, 182986.23214486, 201530.43195363,
        49687.03686643, 211329.11488567, 350499.76588479, 561559.69343975,
       174707.95439883, 163695.94980235, 157998.82088886,  54549.33184373,
       363908.88741341, 166707.82158544, 179247.6089065 , 100849.63630166,
       118022.97474865, 227226.19224841, 117247.39856336, 150233.22368479,
       122007.15195049, 160774.56626804, 144384.68026514, 234857.32987217,
       210137.76340809, 155607.56026491, 188609.78151816, 186869.21213521,
       183603.3813231 , 287414.62338011, 142231.90212468, 130214.53587561,
       193759.34924971, 225028.87743375, 129311.10037232, 143109.01511634,
       251700.43535444, 126020.69051591,  87040.68224899, 150257.63063854,
       269349.90791813, 153596.44245948, 160451.20162369, 280974.23483293,
       262587.48892007, 141382.64967985, 164625.77567679, 207769.04749881,
        85980.52888555, 155178.51374152, 175072.19332215, 153157.39007642,
       194811.34025537, 192614.31847283, 184963.18486375, 177225.32054638,
       212042.22637852, 158511.84962461, 217814.83215472, 180296.88336406,
       106146.67495669, 149711.64674166, 121386.19049878, 138223.70480372,
       298861.20406793, 143815.53622564, 171107.65309469, 174589.03091755,
        72976.35803006, 151713.07826458, 122774.01541382, 294045.57377818,
       197617.35064971, 229333.47317152, 170172.59602048, 262630.44390913,
       296095.64798701, 237912.4658893 , 125975.50113341, 199623.11012629,
       161629.0359828 , 173884.38380967, 224265.98381268, 176253.39908984,
       183928.11540752, 194412.4772972 , 139629.93121135, 132603.45312806,
       276992.81320997, 160593.74110221, 250063.05908   , 194050.57622547,
       184037.25327706, 142197.28879399, 107668.71621935, 183184.96957335,
       109934.64945841, 176669.68035625, 224666.3736063 , 283164.84784854,
       121998.9357029 , 131465.07444919, 150291.044821  , 254001.23157392,
       260350.05462083, 116425.49986421, 192208.35031663, 325739.60159117,
       281061.47116999, 191934.68196724, 180616.30415778, 225460.23351144,
        64318.74938627])

In [52]:
x_test

,LotFrontage,LotArea,BedroomAbvGr,KitchenAbvGr,GarageArea,Street_Grvl,Street_Pave,RoofStyle_Flat,RoofStyle_Gable,RoofStyle_Gambrel,...,RoofStyle_Mansard,RoofStyle_Shed,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl
529,6.454645e-16,2.220035,4,2,0.051559,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
491,4.065156e-01,-0.102911,3,1,-1.090059,0,1,0,1,0,...,0,0,1,0,0,0,0,0,0,0
459,6.454645e-16,-0.350960,3,1,-0.566038,0,1,0,1,0,...,0,0,1,0,0,0,0,0,0,0
279,5.881977e-01,-0.051296,4,1,0.149813,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
655,-2.227875e+00,-0.885645,3,1,-0.977769,0,1,0,1,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,2.248335e-01,0.298980,3,1,1.904350,0,1,0,1,0,...,0,0,0,0,0,0,1,0,0,0
1245,3.610951e-01,0.157666,3,1,0.018808,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1390,-2.269135e-03,-0.141997,3,1,0.318249,0,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
1375,8.607208e-01,0.047522,3,1,1.165105,0,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
638,-1.385307e-01,-0.174369,2,1,-2.212963,0,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0